{
  "openapi": "3.0.3",
  "info": {
    "title": "CubeSigner API",
    "description": "The CubeSigner management and signing service.",
    "contact": {
      "name": "Cubist Inc.",
      "email": "hello@cubist.dev"
    },
    "version": "v0.140.0"
  },
  "servers": [
    {
      "url": "https://gamma.signer.cubist.dev",
      "description": "Testing and staging environment"
    },
    {
      "url": "https://prod.signer.cubist.dev",
      "description": "Production environment"
    }
  ],
  "paths": {
    "/v0/about_me": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "User Info",
        "description": "User Info\n\nRetrieves information about the current user.\n\nPREFER `GET /v0/orgs/{org_id}/user/me`",
        "operationId": "aboutMeLegacy",
        "security": [
          {
            "SignerAuth": [
              ""
            ]
          }
        ]
      }
    },
    "/v0/email/orgs": {
      "get": {
        "tags": [
          "Orgs"
        ],
        "summary": "List accessible organizations.",
        "description": "List accessible organizations.\n\nUnauthenticated endpoint for retrieving all organizations accessible to a user.\nThis information is emailed to the provided email address.\n",
        "operationId": "email_my_orgs",
        "security": [
          {}
        ]
      }
    },
    "/v0/internal/sentry": {
      "post": {
        "tags": [
          "Internal"
        ],
        "summary": "(INTERNAL) Sentry API Proxy",
        "description": "(INTERNAL) Sentry API Proxy",
        "operationId": "sentryApiCallPublic",
        "security": [
          {}
        ]
      }
    },
    "/v0/mmi/v3/.well-known/jwks.json": {
      "get": {
        "tags": [
          "MMI"
        ],
        "summary": "JWKS endpoint for MMI",
        "description": "JWKS endpoint for MMI\n\nReturns the public key used to sign JSON Web Tokens for MMI.",
        "operationId": "mmiJwkSet",
        "security": [
          {}
        ]
      }
    },
    "/v0/mmi/v3/json-rpc": {
      "post": {
        "tags": [
          "MMI"
        ],
        "summary": "MMI JSON-RPC endpoint",
        "description": "MMI JSON-RPC endpoint\n\nHandler for all [MMI JSON-RPC](https://docs.metamask-institutional.io/custodian-integration/integration-docs/api/methods)\nrequests.",
        "operationId": "mmi",
        "security": [
          {
            "SignerAuth": [
              "mmi:*"
            ]
          }
        ]
      }
    },
    "/v0/oauth/token": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Token refresh endpoint, compliant with OAuth.",
        "description": "Token refresh endpoint, compliant with OAuth.\n\nThe body content type can be either 'application/json' or 'application/x-www-form-urlencoded'.\n",
        "operationId": "oauth2TokenRefresh",
        "security": [
          {}
        ]
      }
    },
    "/v0/org/{org_id}": {
      "get": {
        "tags": [
          "Orgs"
        ],
        "summary": "Get Org",
        "description": "Get Org\n\nRetrieves information about an organization.",
        "operationId": "getOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:org:get"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Orgs"
        ],
        "summary": "Update Org",
        "description": "Update Org\n\nUpdate organization attributes (enabled flag, name, and policies).",
        "operationId": "updateOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:*"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/auth_migration/add_identity": {
      "post": {
        "tags": [
          "AuthMigration"
        ],
        "summary": "Associate an OIDC identity with an arbitrary user in org <session.org>.",
        "description": "Associate an OIDC identity with an arbitrary user in org <session.org>.",
        "operationId": "authMigrationIdentityAdd",
        "security": [
          {
            "SignerAuth": [
              "manage:authMigration:identity:add"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/auth_migration/remove_identity": {
      "post": {
        "tags": [
          "AuthMigration"
        ],
        "summary": "Dissociate an OIDC identity from an arbitrary user in org <session.org>.",
        "description": "Dissociate an OIDC identity from an arbitrary user in org <session.org>.",
        "operationId": "authMigrationIdentityRemove",
        "security": [
          {
            "SignerAuth": [
              "manage:authMigration:identity:remove"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/auth_migration/update_users": {
      "post": {
        "tags": [
          "AuthMigration"
        ],
        "summary": "Update existing users' profiles. Currently supports only (re)setting emails.",
        "description": "Update existing users' profiles. Currently supports only (re)setting emails.",
        "operationId": "authMigrationUserUpdate",
        "security": [
          {
            "SignerAuth": [
              "manage:authMigration:user:update"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/ava/sign/{ava_chain}/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign a serialized Avalanche C/X/P-Chain Message",
        "description": "Sign a serialized Avalanche C/X/P-Chain Message\n\nSigns an Avalanche message with a given SecpEth (C-Chain messages) or\nSecpAva (X- and P-Chain messages) key. Currently signing C-Chain messages\nwith SecpEth key must also be explicitly allowed via `AllowRawBlobSigning`\npolicy.\n\nThis is a pre-release feature.",
        "operationId": "avaSerializedTxSign",
        "security": [
          {
            "SignerAuth": [
              "sign:ava"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/ava/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign JSON-encoded Avalanche X- or P-Chain Message",
        "description": "Sign JSON-encoded Avalanche X- or P-Chain Message\n\nSigns an Avalanche message with a given SecpAva key.\nThis is a pre-release feature.",
        "operationId": "avaSign",
        "security": [
          {
            "SignerAuth": [
              "sign:ava"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/babylon/cov/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Babylon Covenant Committee Request",
        "description": "Sign Babylon Covenant Committee Request\n\nSigns transactions relevant to a Babylon covenant committee signer,\ni.e., Schnorr and adaptor signatures for the unbonding, slashing, and\nslash-unbonding outputs of a Babylon staking transaction.",
        "operationId": "babylonCovSign",
        "security": [
          {
            "SignerAuth": [
              "sign:babylon:covenant"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/babylon/eots/nonces/{pubkey}": {
      "post": {
        "tags": [
          "Babylon"
        ],
        "summary": "Create EOTS nonces",
        "description": "Create EOTS nonces\n\nGenerates a set of Babylon EOTS nonces for a specified chain-id, starting at a\nspecified block height.",
        "operationId": "createEotsNonces",
        "security": [
          {
            "SignerAuth": [
              "sign:babylon:eots:nonces"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/babylon/eots/sign/{pubkey}": {
      "post": {
        "tags": [
          "Babylon"
        ],
        "summary": "Create an EOTS signature",
        "description": "Create an EOTS signature\n\nGenerates an EOTS signature for the specified chain-id, block height, and message.",
        "operationId": "eotsSign",
        "security": [
          {
            "SignerAuth": [
              "sign:babylon:eots:sign"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/babylon/registration/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Babylon Staking Registration",
        "description": "Sign Babylon Staking Registration\n\nCreates and signs the data needed to register a Phase-2 or Phase-3\nBabylon stake. This includes the deposit and unbonding transactions,\ntwo slashing transactions, the slashing signatures, and the proof of\npossession.\n\nNote that it is also possible to generate this registration data by\nmaking four calls to the Babylon staking API, plus one call to the\nPSBT signing API to generate the BIP-322 proof of possession. The\nregistration[...]",
        "operationId": "babylonRegistration",
        "security": [
          {
            "SignerAuth": [
              "sign:babylon:registration"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/babylon/staking/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Babylon Staking Transaction",
        "description": "Sign Babylon Staking Transaction\n\nCreates and signs transactions related to Babylon staking (i.e.,\ndeposit, early unbond, withdrawal). The return value is a Pre-Signed\nBitcoin Transaction (PSBT), as defined in BIP-174, which matches the\nformat used in most Babylon tooling.\n\nThe 'deposit' action can be used with either Segwit (i.e., SecpBtc/SecpBtcTest)\nor Taproot (i.e., TaprootBtc/TaprootBtcTest) keys. The remaining actions can be\nused only with Taproot keys.\n\n[...]",
        "operationId": "babylonStaking",
        "security": [
          {
            "SignerAuth": [
              "sign:babylon:staking"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/btc/message/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign a Bitcoin message.",
        "description": "Sign a Bitcoin message.\n\nSigns a message using BIP137 message signing with a given Secp256k1 key.",
        "operationId": "btcMessageSign",
        "security": [
          {
            "SignerAuth": [
              "sign:btc:message:legacy",
              "sign:btc:message:segwit"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/btc/psbt/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign a Partially Signed Bitcoin Transaction (PSBT)",
        "description": "Sign a Partially Signed Bitcoin Transaction (PSBT)\n\nSigns all inputs of the supplied PSBT v0 (BIP-174) that pertain to the\n'pubkey' specified in the request, which can be either a Taproot or a\nSegwit key. For Segwit keys, CubeSigner-specific deterministic tweaking\ncan be applied to 'pubkey' before signing, on a per-input basis. (See the\nCubeSigner documentation for more information on Segwit tweaking.)\n\nWhen calling with a segwit key the required scope is 'sign:bt[...]",
        "operationId": "psbtSign",
        "security": [
          {
            "SignerAuth": [
              "sign:btc:psbt:legacy",
              "sign:btc:psbt:segwit",
              "sign:btc:psbt:taproot"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/btc/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Bitcoin Segwit Transaction",
        "description": "Sign Bitcoin Segwit Transaction\n\nSigns a Bitcoin Segwit transaction with a given key.\nThis is a pre-release feature.",
        "operationId": "btcSign",
        "security": [
          {
            "SignerAuth": [
              "sign:btc:segwit"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/btc/taproot/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Bitcoin Taproot Transaction",
        "description": "Sign Bitcoin Taproot Transaction\n\nSigns a Bitcoin Taproot transaction with a given key.\nThis is a pre-release feature.",
        "operationId": "btcTaprootSign",
        "security": [
          {
            "SignerAuth": [
              "sign:btc:taproot"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/contacts": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "List Contacts",
        "description": "List Contacts\n\nList all contacts in the org.\nAny org member is allowed to list all contacts in the org.",
        "operationId": "listContacts",
        "security": [
          {
            "SignerAuth": [
              "manage:contact:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Contact"
        ],
        "summary": "Create Contact",
        "description": "Create Contact\n\nCreates a new contact in the organization-wide address book. The\nuser making the request is the owner of the contact, giving them edit access\nto the contact along with the org owners.",
        "operationId": "createContact",
        "security": [
          {
            "SignerAuth": [
              "manage:contact:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/contacts/{contact_id}": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Get Contact",
        "description": "Get Contact\n\nReturns the properties of a Contact.",
        "operationId": "getContact",
        "security": [
          {
            "SignerAuth": [
              "manage:contact:get"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Contact"
        ],
        "summary": "Delete Contact",
        "description": "Delete Contact\n\nDelete a contact, specified by its ID.\n\nOnly the contact owner and org owners are allowed to delete contacts.\nAdditionally, the contact's edit policy (if set) must permit the deletion.",
        "operationId": "deleteContact",
        "security": [
          {
            "SignerAuth": [
              "manage:contact:delete"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Contact"
        ],
        "summary": "Update Contact",
        "description": "Update Contact\n\nUpdates an existing contact in the organization-wide address book. Only\nthe contact owner or an org owner can update contacts.\n\n*Updates will overwrite the existing value of the field.*\n",
        "operationId": "updateContact",
        "security": [
          {
            "SignerAuth": [
              "manage:contact:update:name",
              "manage:contact:update:addresses",
              "manage:contact:update:owner",
              "manage:contact:update:metadata",
              "manage:contact:update:editPolicy"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/counts": {
      "get": {
        "tags": [
          "Metrics"
        ],
        "summary": "Get current counts of users and keys within an org.",
        "description": "Get current counts of users and keys within an org.",
        "operationId": "counts",
        "security": [
          {
            "SignerAuth": [
              "manage:org:metrics:query"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/derive_key": {
      "put": {
        "tags": [
          "Keys"
        ],
        "summary": "Derive Key From Long-Lived Mnemonic",
        "description": "Derive Key From Long-Lived Mnemonic\n\nDerives a key of a specified type using a supplied derivation path and an\nexisting long-lived mnemonic.",
        "operationId": "deriveKeyLegacy",
        "deprecated": true,
        "security": [
          {
            "SignerAuth": [
              "manage:key:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/derive_keys": {
      "put": {
        "tags": [
          "Keys"
        ],
        "summary": "Derive Key From New Or Existing Long-Lived Mnemonic",
        "description": "Derive Key From New Or Existing Long-Lived Mnemonic\n\nUses either a new or existing long-lived mnemonic to derive keys of\none or more specified types via specified derivation paths.",
        "operationId": "deriveKey",
        "security": [
          {
            "SignerAuth": [
              "manage:key:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/diffie_hellman/{key_id}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Compute Diffie Hellman shared secret",
        "description": "Compute Diffie Hellman shared secret\n\nFor a set of elliptic curve points (P_1, ..., P_i), computes the Diffie Hellman\nshared secret (Q_1, ..., Qi) = (sk * P_1, ... sk * P_i), for sk the secret key.\nPoints are specified in a curve-dependent format. See CubeSigner documentation\nfor more details.\n\nThe user can optionally specify a NIST P-256 public key, in which case the result\nwill be encrypted to the public key using RFC9180 HPKE(P-256, HKDF-SHA256) with\nAES-256-G[...]",
        "operationId": "diffieHellmanExchange",
        "security": [
          {
            "SignerAuth": [
              "sign:diffieHellman"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/emails/{purpose}": {
      "put": {
        "tags": [
          "Org"
        ],
        "operationId": "configureEmail",
        "security": [
          {
            "SignerAuth": [
              "manage:email"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/evm/eip191/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign EIP-191 Data",
        "description": "Sign EIP-191 Data\n\nSigns a message using EIP-191 personal_sign with a given Secp256k1 key.",
        "operationId": "eip191Sign",
        "security": [
          {
            "SignerAuth": [
              "sign:evm:eip191"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/evm/eip712/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign EIP-712 Typed Data",
        "description": "Sign EIP-712 Typed Data\n\nSigns typed data according to EIP-712 with a given Secp256k1 key.",
        "operationId": "eip712Sign",
        "security": [
          {
            "SignerAuth": [
              "sign:evm:eip712"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/export/{key_id}": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "Get an Org-Export Ciphertext",
        "description": "Get an Org-Export Ciphertext\n\nReturns the export ciphertext associated with the provided key-id.\nIn order to use this API, you must be an org owner and your org must\nbe configured for org export and for API-based export delivery.",
        "operationId": "getOrgExport",
        "security": [
          {
            "SignerAuth": [
              "manage:export:org:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/identity": {
      "get": {
        "tags": [
          "Identity"
        ],
        "summary": "List associated OIDC identities with the current user.",
        "description": "List associated OIDC identities with the current user.\n",
        "operationId": "listOidcIdentities",
        "security": [
          {
            "SignerAuth": [
              "manage:identity:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Identity"
        ],
        "summary": "Associate an OIDC identity with the current user in org <session.org>.",
        "description": "Associate an OIDC identity with the current user in org <session.org>.\n\nAlien users are allowed to call this endpoint, but for them MFA is required\n(unless they are registering an email-otp identity matching their current email);\nadditionally, limits may apply to how many identities that may register.\n",
        "operationId": "addOidcIdentity",
        "security": [
          {
            "SignerAuth": [
              "manage:identity:add"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Identity"
        ],
        "summary": "Remove an OIDC identity from the current user's account in org <session.org>.",
        "description": "Remove an OIDC identity from the current user's account in org <session.org>.\n",
        "operationId": "removeOidcIdentity",
        "security": [
          {
            "SignerAuth": [
              "manage:identity:remove"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/identity/prove": {
      "post": {
        "tags": [
          "Identity"
        ],
        "summary": "Create [IdentityProof] from CubeSigner user session",
        "description": "Create [IdentityProof] from CubeSigner user session\n\nThis route can be used to prove to another party that a user has a\nvalid CubeSigner session.\n\nClients are intended to call this route and pass the returned evidence\nto another service which will verify it by making a request to `/v0/org/<org_id>/identity/verify`.",
        "operationId": "createProofCubeSigner",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/identity/prove/oidc": {
      "post": {
        "tags": [
          "Identity"
        ],
        "summary": "Create [IdentityProof] from OIDC token",
        "description": "Create [IdentityProof] from OIDC token\n\nExchange an OIDC ID token (passed via the `Authorization` header) for a proof of authentication.\n\nThis route can be used to prove to another party that a user has met the\nauthentication requirements (allowed issuers & audiences) for CubeSigner\nwithout leaking their credentials.\n\nClients are intended to call this route and pass the returned evidence to another service\nwhich will verify it by making a request to `/v0/org/<org[...]",
        "operationId": "createProofOidc",
        "security": [
          {
            "Oidc": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/identity/verify": {
      "post": {
        "tags": [
          "Identity"
        ],
        "summary": "Verify identity proof",
        "description": "Verify identity proof\n\nAllows a third-party to validate proof of authentication.\n\nWhen a third-party is provided an [IdentityProof] object, they must check its\nveracity by calling this endpoint",
        "operationId": "verifyProof",
        "security": [
          {
            "SignerAuth": [
              "manage:identity:verify"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/idp/authenticate": {
      "post": {
        "tags": [
          "Login"
        ],
        "summary": "Authenticate",
        "description": "Authenticate\n\nThis endpoint exchanges an email & password for an OIDC token",
        "operationId": "idpAuthenticate",
        "security": []
      }
    },
    "/v0/org/{org_id}/idp/password_reset": {
      "post": {
        "tags": [
          "Account"
        ],
        "summary": "Request Password Reset",
        "description": "Request Password Reset\n\nThis endpoint generates an OIDC token without a signature (of the form `{header}.{payload}.`),\nand sends the signature to the user's email. Client applications can reconstruct the token\nby concatenating the `{header}.{payload}.` with the signature, producing a valid OIDC token of\nthe form `{header}.{payload}.{signature}`. The token can then be used to authenticate the user\nwhen performing the `idp_password_reset_confirm` request.",
        "operationId": "idpPasswordResetRequest",
        "security": []
      },
      "patch": {
        "tags": [
          "Account"
        ],
        "summary": "Confirm Password Reset",
        "description": "Confirm Password Reset\n\nThis endpoint allows IDP users to reset their password\nusing a token they have received in their email.",
        "operationId": "idpPasswordResetConfirm",
        "security": []
      }
    },
    "/v0/org/{org_id}/import_key": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "Create Key-Import Key",
        "description": "Create Key-Import Key\n\nGenerate an ephemeral key that a client can use for key-import encryption.",
        "operationId": "createKeyImportKey",
        "security": [
          {
            "SignerAuth": [
              "manage:key:import"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Keys"
        ],
        "summary": "Import Key",
        "description": "Import Key\n\nSecurely imports an existing key using a previously generated key-import key.",
        "operationId": "importKey",
        "security": [
          {
            "SignerAuth": [
              "manage:key:import"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/info": {
      "get": {
        "tags": [
          "Orgs"
        ],
        "summary": "Public Org Info",
        "description": "Public Org Info\n\nUnauthenticated endpoint that returns publicly-available information about an organization.\n",
        "operationId": "public_org_info",
        "security": [
          {}
        ]
      }
    },
    "/v0/org/{org_id}/internal/esplora": {
      "post": {
        "tags": [
          "Internal"
        ],
        "summary": "(INTERNAL) Esplora API Proxy",
        "description": "(INTERNAL) Esplora API Proxy",
        "operationId": "esploraApiCall",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/internal/sentry": {
      "post": {
        "tags": [
          "Internal"
        ],
        "summary": "(INTERNAL) Authenticated Sentry API Proxy",
        "description": "(INTERNAL) Authenticated Sentry API Proxy",
        "operationId": "sentryApiCall",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/invitation/accept": {
      "post": {
        "tags": [
          "Accounts"
        ],
        "summary": "Accept an invitation",
        "description": "Accept an invitation\n\nThis endpoint allows idp users to register using a token they have received in their email",
        "operationId": "invitationAccept",
        "security": []
      }
    },
    "/v0/org/{org_id}/invite": {
      "post": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Invite User",
        "description": "Invite User\n\nCreates a new user in an existing org and sends that user an invite email.",
        "operationId": "invite",
        "security": [
          {
            "SignerAuth": [
              "manage:org:inviteUser"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/keys": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "List Keys",
        "description": "List Keys\n\nGets the list of accessible keys in a given org (to org owner, all org keys\nare accessible; to members, only their own keys are accessible).\n\nIf a search condition is, the result will contain only the keys whose either\nmaterial ID or metadata contain the search condition string.\n\nNOTE that if pagination is used and a page limit is set, the returned result\nset may contain either FEWER or MORE elements than the requested page limit.",
        "operationId": "listKeysInOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:key:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Keys"
        ],
        "summary": "Create Key",
        "description": "Create Key\n\nCreates one or more new keys of the specified type.",
        "operationId": "createKey",
        "security": [
          {
            "SignerAuth": [
              "manage:key:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/keys/{key_id}": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "Get Key",
        "description": "Get Key\n\nReturns the properties of a key.",
        "operationId": "getKeyInOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:key:get"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Keys"
        ],
        "summary": "Delete Key",
        "description": "Delete Key\n\nDeletes a key specified by its ID.\n\nOnly the key owner and org owners are allowed to delete keys.\nAdditionally, the role's edit policy (if set) must permit the update.",
        "operationId": "deleteKey",
        "security": [
          {
            "SignerAuth": [
              "manage:key:delete"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Keys"
        ],
        "summary": "Update Key",
        "description": "Update Key\n\nEnable or disable a key.  The user must be the owner of the key or\norganization to perform this action.\n\nFor each requested update, the session must have the corresponding 'manage:key:update:_' scope;\nif no updates are requested, the session must have 'manage:key:get'.",
        "operationId": "updateKey",
        "security": [
          {
            "SignerAuth": [
              "manage:key:update:enabled",
              "manage:key:update:metadata",
              "manage:key:update:policy",
              "manage:key:update:owner",
              "manage:key:update:editPolicy"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/keys/{key_id}/roles": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "List Key Roles",
        "description": "List Key Roles\n\nGet all roles the key is in",
        "operationId": "listKeyRoles",
        "security": [
          {
            "SignerAuth": [
              "manage:key:list_roles"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/keys/{key_id}/tx": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "List Historical Transactions",
        "description": "List Historical Transactions\n\nReturns a sorted, paginated list of transactions signed by a given key,\nordered from most recent first.",
        "operationId": "listHistoricalKeyTx",
        "security": [
          {
            "SignerAuth": [
              "manage:key:history:tx:list"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/keys/{key_type}/{material_id}": {
      "get": {
        "tags": [
          "Keys"
        ],
        "summary": "Get Key by Material ID",
        "description": "Get Key by Material ID\n\nReturns the properties of a key.",
        "operationId": "getKeyByMaterialId",
        "security": [
          {
            "SignerAuth": [
              "manage:key:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/metrics": {
      "post": {
        "tags": [
          "Metrics"
        ],
        "summary": "Query org metrics.",
        "description": "Query org metrics.\n\nMetrics summarize usage information about your CubeSigner organization over time. For example,\nyou can call this endpoint find out:\n\n- the average number of keys over the last month,\n- the average number monthly users over the last year,\n- the total number of transactions signed last week,\n- how the number of different API requests was trending day-by-day over the last week/month/year, etc.\n\nEach metric kind can have one or more dimensions, t[...]",
        "operationId": "queryMetrics",
        "security": [
          {
            "SignerAuth": [
              "manage:org:metrics:query"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mfa": {
      "get": {
        "tags": [
          "MFA"
        ],
        "summary": "List Pending MFA Requests",
        "description": "List Pending MFA Requests\n\nRetrieves and returns all pending MFA requests that are accessible to the current session,\ni.e., those created by the current session identity plus those in which the current user\nis listed as an approver",
        "operationId": "mfaList",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:list"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mfa/{mfa_id}": {
      "get": {
        "tags": [
          "MFA"
        ],
        "summary": "Get Pending MFA Request",
        "description": "Get Pending MFA Request\n\nRetrieves and returns a pending MFA request by its id.",
        "operationId": "mfaGet",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      },
      "patch": {
        "tags": [
          "MFA"
        ],
        "summary": "Approve or Reject MFA Request",
        "description": "Approve or Reject MFA Request\n\nApprove or reject request after logging in with CubeSigner.\n\nIf approving, adds the currently-logged user as an approver\nof a pending MFA request of the [Status::RequiredApprovers] kind. If the required number of\napprovers is reached, the MFA request is approved; the confirmation receipt can be used to\nresume the original HTTP request.\n\nIf rejecting, immediately deletes the pending MFA request.",
        "operationId": "mfaVoteCs",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:vote:cs"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mfa/{mfa_id}/email": {
      "post": {
        "tags": [
          "MFA"
        ],
        "summary": "Initiate an Email OTP MFA Approval/Rejection",
        "description": "Initiate an Email OTP MFA Approval/Rejection\n\nInitiates the approval/rejection process of an MFA Request using Email OTP.",
        "operationId": "mfaEmailInit",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:vote:email"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "MFA"
        ],
        "summary": "Finalize a Email OTP MFA Approval/Rejection.",
        "description": "Finalize a Email OTP MFA Approval/Rejection.\n\nThe request should contain the full JWT obtained by concatenating the\npartial token returned by the `mfa_email_init` endpoint and the signature\nemailed to the user issuing the request.\n\nIf approving, adds an approver to a pending MFA request.\nIf the required number of approvers is reached, the MFA request is approved;\nthe confirmation receipt can be used to resume the original HTTP request.\n\nIf rejecting, immediately[...]",
        "operationId": "mfaVoteEmailComplete",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:vote:email"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mfa/{mfa_id}/fido": {
      "post": {
        "tags": [
          "MFA"
        ],
        "summary": "Initiate a FIDO MFA Approval/Rejection",
        "description": "Initiate a FIDO MFA Approval/Rejection\n\nInitiates the approval/rejection process of an MFA Request using FIDO.",
        "operationId": "mfaFidoInit",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:vote:fido"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "MFA"
        ],
        "summary": "Finalize a FIDO MFA Approval/Rejection",
        "description": "Finalize a FIDO MFA Approval/Rejection\n\nIf approving, adds an approver to a pending MFA request.\nIf the required number of approvers is reached, the MFA request is approved;\nthe confirmation receipt can be used to resume the original HTTP request.\n\nIf rejecting, immediately deletes the pending MFA request.",
        "operationId": "mfaVoteFidoComplete",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:vote:fido"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mfa/{mfa_id}/totp": {
      "patch": {
        "tags": [
          "MFA"
        ],
        "summary": "Approve/Reject a TOTP MFA Request",
        "description": "Approve/Reject a TOTP MFA Request\n\nIf approving, adds the current user as approver to a pending MFA request by\nproviding TOTP code. If the required number of approvers is reached, the MFA request is\napproved; the confirmation receipt can be used to resume the original HTTP request.\n\nIf rejecting, immediately deletes the pending MFA request.",
        "operationId": "mfaVoteTotp",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:vote:totp"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mmi/v3/messages": {
      "get": {
        "tags": [
          "MMI"
        ],
        "summary": "List pending MMI requests",
        "description": "List pending MMI requests\n\nRetrieves and returns all pending MMI messages accessible to the current session identity, i.e.,\n- a role session can access only the messages created by that role\n- a user session can access the messages created by either that user or any role which the user is a member of",
        "operationId": "mmiMessageList",
        "security": [
          {
            "SignerAuth": [
              "manage:mmi:list"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mmi/v3/messages/{msg_id}": {
      "get": {
        "tags": [
          "MMI"
        ],
        "summary": "Get an MMI request",
        "description": "Get an MMI request\n\nRetrieves a pending MMI request by its ID.",
        "operationId": "mmiMessageGet",
        "security": [
          {
            "SignerAuth": [
              "manage:mmi:get"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "MMI"
        ],
        "summary": "Delete an MMI request",
        "description": "Delete an MMI request\n\nRejects an existing MMI request and then deletes it from the database.",
        "operationId": "mmiMessageDelete",
        "security": [
          {
            "SignerAuth": [
              "manage:mmi:delete"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mmi/v3/messages/{msg_id}/reject": {
      "post": {
        "tags": [
          "MMI"
        ],
        "summary": "Reject an MMI request",
        "description": "Reject an MMI request\n\nRejects a pending MMI request. The record of the MMI request is kept in\nthe database until it expires or is explicitly deleted.\n\nReturns the updated request information.",
        "operationId": "mmiMessageReject",
        "security": [
          {
            "SignerAuth": [
              "manage:mmi:reject"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/mmi/v3/messages/{msg_id}/sign": {
      "post": {
        "tags": [
          "MMI"
        ],
        "summary": "Approve and sign an MMI request",
        "description": "Approve and sign an MMI request\n\nSigns a pending request that was generated through the MMI JSON RPC endpoint.\nThe signature is stored with the pending message and the updated request info is returned.\n\nThe message should be associated with the organization this is called from,\nand the user should be the owner of the corresponding message's key.",
        "operationId": "mmiMessageSign",
        "security": [
          {
            "SignerAuth": [
              "sign:mmi"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/oauth2/twitter": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Mint an OIDC ID token for Twitter",
        "description": "Mint an OIDC ID token for Twitter\n\nThis function acts identically to Twitter's [`oauth2/token`](https://developer.twitter.com/en/docs/authentication/api-reference/token) endpoint,\nbut extends the output with an `id_token`.\n\nThis `id_token` can then be used with any CubeSigner endpoint that requires an OIDC token.\n\n> [!IMPORTANT]\n> This endpoint will fail unless the org is configured to allow the issuer `https://shim.oauth2.cubist.dev/twitter` and client ID being u[...]",
        "operationId": "oauth2Twitter",
        "security": [
          {}
        ]
      }
    },
    "/v0/org/{org_id}/oidc": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Login with OIDC",
        "description": "Login with OIDC\n\nExchange an OIDC ID token (passed via the `Authorization` header) for a signer session.\n\nMFA is required when:\n- an MFA policy is explicitly attached to the user logging in\n(e.g., an org owner can do that at user creation time to require certain kind of MFA)\n- the user has at least 1 MFA factor configured",
        "operationId": "oidcAuth",
        "security": [
          {
            "Oidc": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/oidc/email-otp": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Initiate login via email token",
        "description": "Initiate login via email token\n\nThis endpoint generates an OIDC token without a signature (of the form `header.payload.`), and sends the signature to the user's email.\nClient applications can reconstruct the token by concatenating the `partial_token` with the signature, producing a valid OIDC token of the form `header.payload.signature`\nThe token can then be used to authenticate the user.\n\n> [!IMPORTANT]\n> For this endpoint to succeed, the org must be configured to[...]",
        "operationId": "emailOtpAuth",
        "security": [
          {}
        ]
      }
    },
    "/v0/org/{org_id}/oidc/siwe": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Initiate login via Sign-in With Ethereum (SIWE).",
        "description": "Initiate login via Sign-in With Ethereum (SIWE).\n\nThis endpoint generates a challenge which can be answered (via the corresponding PATCH endpoint)\nto obtain an OIDC token. The OIDC token can then be exchanged for a user session via the standard\nOIDC auth route.\n\n> [!IMPORTANT]\n> For this endpoint to succeed, the org must be configured to:\n> Allow the issuer `https://shim.oauth2.cubist.dev/siwe` with the Org ID as the client ID",
        "operationId": "siweInit",
        "security": [
          {}
        ]
      },
      "patch": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Complete login via Sign-in With Ethereum (SIWE)",
        "description": "Complete login via Sign-in With Ethereum (SIWE)\n\nIf the challenge (issued by the corresponding POST endpoint) is answered correctly, this endpoint\ngenerates an OIDC token that can then be exchanged for a user session via the standard OIDC auth route.\n\n> [!IMPORTANT]\n> For this endpoint to succeed, the org must be configured to:\n> Allow the issuer `https://shim.oauth2.cubist.dev/siwe` with the Org ID as the client ID",
        "operationId": "siweComplete",
        "security": [
          {}
        ]
      }
    },
    "/v0/org/{org_id}/oidc/telegram": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Allows a user to authenticate with the telegram API using the tgWebAppData value",
        "description": "Allows a user to authenticate with the telegram API using the tgWebAppData value\nThe token has the following properties:\n- The `sub` field is the telegram user ID\n- The `iss` field depends on the chosen environment:\n- `https://shim.oauth2.cubist.dev/telegram/production` for the production environment\n- `https://shim.oauth2.cubist.dev/telegram/test` for the test environment\n- The `aud` field is the provided telegram bot ID\n- The `exp` field is derived from the `auth[...]",
        "operationId": "telegramAuth",
        "security": [
          {}
        ]
      }
    },
    "/v0/org/{org_id}/orgs": {
      "post": {
        "tags": [
          "Orgs"
        ],
        "summary": "Create Org",
        "description": "Create Org\n\nCreates a new organization. The new org is a child of the\ncurrent org and inherits its key-export policy. The new org\nis created with one owner, the caller of this API.",
        "operationId": "createOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:org:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policies": {
      "get": {
        "tags": [
          "Policies"
        ],
        "summary": "List Policies",
        "description": "List Policies\n\nReturns the list of all policies in the Org.",
        "operationId": "listPolicies",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Policies"
        ],
        "summary": "Create Policy",
        "description": "Create Policy\n\nCreates a new named policy in the organization. The user making the request is the\nowner of the policy, giving them edit access to the policy along with the org owners.",
        "operationId": "createPolicy",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policies/{policy_id}": {
      "delete": {
        "tags": [
          "Policies"
        ],
        "summary": "Delete Policy",
        "description": "Delete Policy\n\nDelete the named policy with the given name or id.",
        "operationId": "deletePolicy",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:delete"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Policies"
        ],
        "summary": "Update Policy",
        "description": "Update Policy\n\nUpdates the policy with the given name or id.",
        "operationId": "updatePolicy",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:update",
              "manage:policy:update:rule",
              "manage:policy:update:owner",
              "manage:policy:update:name",
              "manage:policy:update:editPolicy"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policies/{policy_id}/logs": {
      "post": {
        "tags": [
          "Policies"
        ],
        "summary": "Get Policy Logs",
        "description": "Get Policy Logs\n\nReturns the logs for the given policy, within the given timeframe.",
        "operationId": "getPolicyLogs",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:logs:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policies/{policy_id}/{version}": {
      "get": {
        "tags": [
          "Policies"
        ],
        "summary": "Get Policy",
        "description": "Get Policy\n\nReturns the specified version or latest of a named policy with the given name or id.",
        "operationId": "getPolicy",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policies/{policy_id}/{version}/invoke": {
      "post": {
        "tags": [
          "Policies"
        ],
        "summary": "Invoke Policy",
        "description": "Invoke Policy\n\nInvokes the [NamedPolicy] with the given ID with the given request information.\nIt is only supported for Wasm policies.",
        "operationId": "invokePolicy",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:invoke"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policy/import_key": {
      "get": {
        "tags": [
          "Policies"
        ],
        "summary": "Create Policy Import Key",
        "description": "Create Policy Import Key\n\nGenerate an ephemeral key that a client can use for encrypting data related to Wasm\npolicies (e.g., policy secrets).",
        "operationId": "createPolicyImportKey",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:createImportKey"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policy/secrets": {
      "get": {
        "tags": [
          "Policies"
        ],
        "summary": "Get the org-wide policy secrets.",
        "description": "Get the org-wide policy secrets.\n\nNote that this only returns the keys for the secrets, omiting the values.\nThe values are secret and are not accessible outside Wasm policy execution.",
        "operationId": "getPolicySecrets",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:secrets:get"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Policies"
        ],
        "summary": "Update org-level policy secrets",
        "description": "Update org-level policy secrets\n\nThe provided secrets will replace any existing org-level secrets.\nIt fails if the secrets weren't previously created.",
        "operationId": "updatePolicySecrets",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:secrets:update",
              "manage:policy:secrets:update:values",
              "manage:policy:secrets:update:editPolicy"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policy/secrets/{secret_name}": {
      "put": {
        "tags": [
          "Policies"
        ],
        "summary": "Create or overwrite an org-level policy secret",
        "description": "Create or overwrite an org-level policy secret",
        "operationId": "setPolicySecret",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:secrets:update:values"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Policies"
        ],
        "summary": "Delete an org-level policy secret",
        "description": "Delete an org-level policy secret",
        "operationId": "deletePolicySecret",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:secrets:update:values"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/policy/wasm": {
      "post": {
        "tags": [
          "Policies"
        ],
        "summary": "Upload Wasm Policy",
        "description": "Upload Wasm Policy\n\nReturns a signed URL for uploading a wasm policy to CubeSigner. The policy will be\ndeleted if not attached to a [NamedPolicy] soon after the upload has been completed.",
        "operationId": "uploadWasmPolicy",
        "security": [
          {
            "SignerAuth": [
              "manage:policy:wasm:upload"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List Roles",
        "description": "List Roles\n\nRetrieves all roles in an organization that the current user is allowed to access.",
        "operationId": "listRoles",
        "security": [
          {
            "SignerAuth": [
              "manage:role:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Roles"
        ],
        "summary": "Create Role",
        "description": "Create Role\n\nCreates a new role in an organization. Unless the logged-in user\nis the owner, they are automatically added to the newly created role.",
        "operationId": "createRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get Role",
        "description": "Get Role\n\nRetrieves information about a role in an organization",
        "operationId": "getRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:get"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Delete Role",
        "description": "Delete Role\n\nDeletes a role in an organization.\n\nOnly users in the role can perform this action.\nAdditionally, the role's edit policy (if set) must permit the update.",
        "operationId": "deleteRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:delete"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Roles"
        ],
        "summary": "Update Role",
        "description": "Update Role\n\nEnables or disables a role (this requires the `manage:role:update:enable` scope).\nUpdates the role's policies (this requires the `manage:role:update:policy` scope).\nUpdates the role's edit policies (this requires the `manage:role:update:editPolicy` scope).\n\nThe user must be in the role or an owner of the organization.\nAdditionally, the role's edit policy (if set) must permit the update.",
        "operationId": "updateRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:update:enable",
              "manage:role:update:policy",
              "manage:role:update:editPolicy"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/add_keys": {
      "put": {
        "tags": [
          "Keys In Role"
        ],
        "summary": "Add Keys",
        "description": "Add Keys\n\nAdds a list of existing keys to an existing role.\n\nThe key owner is allowed to add their key to any role that they are in.\n\nIn \"org custody\" model only, org owners are allowed to add any key to any role.\n\nIn all cases: the role's edit policy, as well as the edit policy of each of the keys, must permit the update.\n\nEach request to this endpoint can add, at maximum, 32 keys.",
        "operationId": "addKeysToRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:update:key:add"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/add_user/{user_id}": {
      "put": {
        "tags": [
          "Users In Role"
        ],
        "summary": "Add User",
        "description": "Add User\n\nAdds an existing user to an existing role.\n\nOnly users in the role or org owners can add users to a role.\nAdditionally, the role's edit policy (if set) must permit the update.",
        "operationId": "addUserToRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:update:user:add"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/keys": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List Role Keys",
        "description": "List Role Keys\n\nReturns an array of all keys in a role.",
        "operationId": "listRoleKeys",
        "security": [
          {
            "SignerAuth": [
              "manage:role:get:keys"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/keys/{key_id}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get a Key in Role",
        "description": "Get a Key in Role\n\nReturns the key-in-role information for a given key and role. If `details` is set to `true`,\nthis endpoint returns detailed key information.",
        "operationId": "getRoleKey",
        "security": [
          {
            "SignerAuth": [
              "manage:role:get:keys"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Keys In Role"
        ],
        "summary": "Remove Key",
        "description": "Remove Key\n\nRemoves a given key from a role.\n\nOnly users in the role or org owners can remove keys from a role.\nAdditionally, both the role's and the key's edit policy must permit the update.",
        "operationId": "removeKeyFromRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:update:key:remove"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/tokens": {
      "post": {
        "tags": [
          "Role Access Tokens"
        ],
        "summary": "Create Token",
        "description": "Create Token\n\nCreates a new access token for a given role (to be used as \"API Key\" for all signing actions).\nThe `restricted_actions` field on the [Role] determines the membership role that is required to\ncreate tokens.",
        "operationId": "createRoleToken",
        "security": [
          {
            "SignerAuth": [
              "manage:session:create"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/tx": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List Historical Transactions",
        "description": "List Historical Transactions\n\nReturns a sorted, paginated list of transactions signed by the given role,\nordered from most recent first.",
        "operationId": "listHistoricalRoleTx",
        "security": [
          {
            "SignerAuth": [
              "manage:role:history:tx:list"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/users": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List Role Users.",
        "description": "List Role Users.\n\nReturns an array of all users who have access to a role.",
        "operationId": "listRoleUsers",
        "security": [
          {
            "SignerAuth": [
              "manage:role:get:users"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/roles/{role_id}/users/{user_id}": {
      "delete": {
        "tags": [
          "Users In Role"
        ],
        "summary": "Remove User",
        "description": "Remove User\n\nRemoves an existing user from an existing role.\n\nOnly users in the role or org owners can remove users from a role.\nAdditionally, the role's edit policy (if set) must permit the update.",
        "operationId": "removeUserFromRole",
        "security": [
          {
            "SignerAuth": [
              "manage:role:update:user:remove"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/session": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "List sessions",
        "description": "List sessions\n\nIf no query parameters are provided, all active sessions for the current user are returned.\n\nIf a `role` query parameter is provided, all active sessions for the selected role are returned\n(asserting first that the current user has permissions to read sessions for that role).\n",
        "operationId": "listSessions",
        "security": [
          {
            "SignerAuth": [
              "manage:session:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Sessions"
        ],
        "summary": "Create new user session (management and/or signing)",
        "description": "Create new user session (management and/or signing)\n\nCreates a new user session, silently truncating requested session and auth lifetimes to be at\nmost requestor's session and auth lifetime, respectively. To extend the requested lifetimes past\nthe requestor's, set the `extend_lifetimes` flag in the request body (in which case MFA will\nbe required).\n",
        "operationId": "createSession",
        "security": [
          {
            "SignerAuth": [
              "manage:session:create"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Sessions"
        ],
        "summary": "Revoke ALL existing user or role session(s)",
        "description": "Revoke ALL existing user or role session(s)\n\nImmediately revokes existing sessions, preventing them from being used or refreshed.\n\nIf no query params are provided, **ALL** sessions for the **CURRENT USER** are revoked\n(to revoke just the current user session, use `DELETE /v0/org/<org_id>/session/self`)\n\nIf a `role` query parameter is provided, **ALL** session for **THAT ROLE** are revoked\n(if the current user has permissions to revoke sessions for the role).\n",
        "operationId": "revokeSessions",
        "security": [
          {
            "SignerAuth": [
              "manage:session:revoke"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/session/self": {
      "delete": {
        "tags": [
          "Sessions"
        ],
        "summary": "Revoke current session",
        "description": "Revoke current session\n\nImmediately revokes the current session, preventing it from being used or refreshed",
        "operationId": "revokeCurrentSession",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/session/{session_id}": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "Get session information",
        "description": "Get session information",
        "operationId": "getSession",
        "security": [
          {
            "SignerAuth": [
              "manage:session:get"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Sessions"
        ],
        "summary": "Revoke a session",
        "description": "Revoke a session\n\nImmediately revokes an existing session, preventing it from being used or refreshed",
        "operationId": "revokeSession",
        "security": [
          {
            "SignerAuth": [
              "manage:session:revoke"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/solana/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Solana Message",
        "description": "Sign Solana Message\n\nSigns a Solana message with a given key.\nThis is a pre-release feature.",
        "operationId": "solanaSign",
        "security": [
          {
            "SignerAuth": [
              "sign:solana"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/sui/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign a serialized SUI transaction.",
        "description": "Sign a serialized SUI transaction.\n\nThis is a pre-release feature.",
        "operationId": "suiSign",
        "security": [
          {
            "SignerAuth": [
              "sign:sui"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/tendermint/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign a tendermint message.",
        "description": "Sign a tendermint message.\n\nSigns the given base-64 encoded vote or proposal with the given tendermint key.",
        "operationId": "tendermintSign",
        "security": [
          {
            "SignerAuth": [
              "sign:tendermint"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/token/keys": {
      "get": {
        "tags": [
          "Role Access Tokens"
        ],
        "summary": "Get Token-Accessible Keys",
        "description": "Get Token-Accessible Keys\n\nRetrieves the keys that a user or role session can access.",
        "operationId": "listTokenKeys",
        "security": [
          {
            "SignerAuth": [
              "manage:key:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "User Info",
        "description": "User Info\n\nRetrieves information about the current user.",
        "operationId": "aboutMe",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me/email": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Initiate Reset Verified Email Flow",
        "description": "Initiate Reset Verified Email Flow\n",
        "operationId": "userResetEmailInit",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:email"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User"
        ],
        "summary": "Finalize a Reset Verified Email Flow",
        "description": "Finalize a Reset Verified Email Flow",
        "operationId": "userResetEmailComplete",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:email"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me/export": {
      "get": {
        "tags": [
          "User Export"
        ],
        "summary": "List outstanding user-export requests",
        "description": "List outstanding user-export requests",
        "operationId": "userExportList",
        "security": [
          {
            "SignerAuth": [
              "manage:export:user:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "User Export"
        ],
        "summary": "Initiate a user-export request",
        "description": "Initiate a user-export request\n\nThis starts a delay (whose length is determined by Org-wide settings)\nbefore export can be completed, and returns a ticket that can be used\nto complete the export once the timer has expired.\n\nOnly one user-export request can be active for a given key. If there\nis already an active export, this endpoint will return an error. To\ncreate a new request, first delete the existing one.",
        "operationId": "userExportInit",
        "security": [
          {
            "SignerAuth": [
              "export:user:init"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "User Export"
        ],
        "summary": "Delete an existing user-export request",
        "description": "Delete an existing user-export request",
        "operationId": "userExportDelete",
        "security": [
          {
            "SignerAuth": [
              "manage:export:user:delete"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User Export"
        ],
        "summary": "Complete a user-export request",
        "description": "Complete a user-export request\n\nThis endpoint can be called only after initiating a user-export request via\nthe `user_export_init` API, and only within the subsequent export window\n(i.e., after the export delay has passed and before the request has expired).\n\nTo check on the status of an export request, see the `user_export_list` API.",
        "operationId": "userExportComplete",
        "security": [
          {
            "SignerAuth": [
              "export:user:complete"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me/fido": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Initiate registration of a FIDO key.",
        "description": "Initiate registration of a FIDO key.\n\nIf a discoverable key is requested, user verification (PIN) is required.\n\nGenerates a challenge that must be answered to prove ownership of a key.",
        "operationId": "userRegisterFidoInit",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:fido"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User"
        ],
        "summary": "Finalize registration of a FIDO key",
        "description": "Finalize registration of a FIDO key\n\nAccepts the response to the challenge generated by the POST to this endpoint.",
        "operationId": "userRegisterFidoComplete",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:fido"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me/fido/{fido_id}": {
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete FIDO key",
        "description": "Delete FIDO key\n\nDeletes a FIDO key from the user's account (if the key is not the sole MFA factor). MFA is always required.",
        "operationId": "userDeleteFido",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:unregister:fido"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me/totp": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Initialize TOTP Reset",
        "description": "Initialize TOTP Reset\n\nCreates a new TOTP challenge that must be answered to prove that the new TOTP\nwas successfully imported into an authenticator app.\n\nThis operation is allowed if EITHER\n- the user account is not yet initialized and no TOTP is already set, OR\n- the user has not configured any auth factors;\notherwise, MFA is required.",
        "operationId": "userResetTotpInit",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:totp"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete TOTP",
        "description": "Delete TOTP\n\nDeletes TOTP from the user's account (if TOTP is not the sole MFA factor). MFA is always required.\n",
        "operationId": "userDeleteTotp",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:unregister:totp"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User"
        ],
        "summary": "Finalize resetting TOTP",
        "description": "Finalize resetting TOTP\n\nChecks if the response contains the correct TOTP code corresponding to the\nchallenge generated by the POST method of this endpoint.",
        "operationId": "userResetTotpComplete",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:totp"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/user/me/totp/verify": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Verify TOTP",
        "description": "Verify TOTP\n\nChecks if a given code matches the current TOTP code for the current user.\nErrors with 403 if the current user has not set up TOTP or the code fails verification.",
        "operationId": "userVerifyTotp",
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:verify:totp"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/users": {
      "get": {
        "tags": [
          "Users In Org"
        ],
        "summary": "List users in organization",
        "description": "List users in organization\n\nIf a query is defined, the result will contain only the users whose name or\nemail contain the query string. NOTE that if pagination is used and a page\nlimit is set, the returned result set may contain FEWER elements than the\nrequested page limit.\n",
        "operationId": "listUsersInOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:org:user:list"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Add a third-party user to the org",
        "description": "Add a third-party user to the org\n",
        "operationId": "createOidcUser",
        "security": [
          {
            "SignerAuth": [
              "manage:org:addUser"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/users/email/{email}": {
      "get": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Get user by email.",
        "description": "Get user by email.\n\nThe search includes all users and their third-party identities.",
        "operationId": "getUserInOrgByEmail",
        "security": [
          {
            "SignerAuth": [
              "manage:org:user:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/users/oidc": {
      "delete": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Remove a third-party user from the org",
        "description": "Remove a third-party user from the org\n",
        "operationId": "deleteOidcUser",
        "security": [
          {
            "SignerAuth": [
              "manage:org:deleteUser"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/users/oidc/{iss}/{sub}": {
      "get": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Get a user by their OIDC identity",
        "description": "Get a user by their OIDC identity\n\nRetrieves a user in the organization by their OIDC issuer and subject.",
        "operationId": "getUserInOrgByOidc",
        "security": [
          {
            "SignerAuth": [
              "manage:org:user:get"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/users/reset_mfa": {
      "post": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Initialize MFA reset for user",
        "description": "Initialize MFA reset for user",
        "operationId": "resetMemberMfa",
        "security": [
          {
            "SignerAuth": [
              "manage:org:resetMfa"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Complete MFA reset for user",
        "description": "Complete MFA reset for user",
        "operationId": "completeResetMemberMfa",
        "security": [
          {
            "Oidc": []
          }
        ]
      }
    },
    "/v0/org/{org_id}/users/{user_id}": {
      "get": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Get user by id",
        "description": "Get user by id\n",
        "operationId": "getUserInOrg",
        "security": [
          {
            "SignerAuth": [
              "manage:org:user:get"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Remove a user from the org",
        "description": "Remove a user from the org\n",
        "operationId": "deleteUser",
        "security": [
          {
            "SignerAuth": [
              "manage:org:deleteUser"
            ]
          }
        ]
      }
    },
    "/v0/org/{org_id}/users/{user_id}/membership": {
      "patch": {
        "tags": [
          "Users In Org"
        ],
        "summary": "Update a user's membership in the org",
        "description": "Update a user's membership in the org\n\nEnable/disable another user in the org, or change their membership role.",
        "operationId": "updateUserMembership",
        "security": [
          {
            "SignerAuth": [
              "manage:org:updateMembership"
            ]
          }
        ]
      }
    },
    "/v0/passkey": {
      "post": {
        "tags": [
          "Login"
        ],
        "summary": "Initiate Login with Passkey",
        "description": "Initiate Login with Passkey\n\nThe response contains a FIDO challenge that the client must answer with any of their\ndiscoverable credentials.  The answer should be submitted with the corresponding PATCH request.",
        "operationId": "passkeyAuthInit",
        "security": [
          {}
        ]
      },
      "patch": {
        "tags": [
          "Login"
        ],
        "summary": "Complete Login with Passkey",
        "description": "Complete Login with Passkey\n\nThe request should contain an answer to the challenge issued by the corresponding POST request.\nThe challenge may be answered with any of the user's discoverable credentials; if the credential\nincluded in the answer is registered with a user and an organization, the response will contain\na CubeSigner session (with the parameters supplied in the previous POST request) for that user\nin that organization.",
        "operationId": "passkeyAuthComplete",
        "security": [
          {}
        ]
      }
    },
    "/v0/private/policy-execute/{policy_name}": {
      "post": {
        "tags": [
          "policy-engine"
        ],
        "summary": "The policy_execute API endpoint is intended to demonstrate that the signer",
        "description": "The policy_execute API endpoint is intended to demonstrate that the signer\ncan use the policy engine, by way of the PolicyEngineClient.",
        "operationId": "policy-execute",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v0/user/me/fido": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Initiate registration of a FIDO key",
        "description": "Initiate registration of a FIDO key\n\nDEPRECATED. Use `POST /v0/org/{org_id}/user/me/fido` instead.\n\nGenerates a challenge that must be answered to prove ownership of a key",
        "operationId": "registerFidoInitLegacy",
        "deprecated": true,
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:fido"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User"
        ],
        "summary": "Finalize registration of a FIDO key",
        "description": "Finalize registration of a FIDO key\n\nDEPRECATED. Use `PATCH /v0/org/{org_id}/user/me/fido` instead.\n\nAccepts the response to the challenge generated by the POST to this endpoint.",
        "operationId": "registerFidoCompleteLegacy",
        "deprecated": true,
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:fido"
            ]
          }
        ]
      }
    },
    "/v0/user/me/totp": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Initialize TOTP Reset",
        "description": "Initialize TOTP Reset\n\nDEPRECATED. Use `POST /v0/org/{org_id}/user/me/totp` instead.\n\nCreates a new TOTP challenge that must be answered to prove that the new TOTP\nwas successfully imported into an authenticator app.\n\nThis operation is allowed if EITHER\n- the user account is not yet initialized and no TOTP is already set, OR\n- the user has not configured any auth factors;\notherwise, MFA is required.",
        "operationId": "resetTotpInitLegacy",
        "deprecated": true,
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:totp"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "User"
        ],
        "summary": "Finalize resetting TOTP",
        "description": "Finalize resetting TOTP\n\nDEPRECATED. Use `PATCH /v0/org/{org_id}/user/me/totp` instead.\n\nChecks if the response contains the correct TOTP code corresponding to the\nchallenge generated by the POST method of this endpoint.",
        "operationId": "resetTotpCompleteLegacy",
        "deprecated": true,
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:register:totp"
            ]
          }
        ]
      }
    },
    "/v0/user/me/totp/verify": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Verify TOTP",
        "description": "Verify TOTP\n\nDEPRECATED. Use `POST /v0/org/{org_id}/user/me/totp/verify` instead.\n\nChecks if a given code matches the current TOTP code for the current user.\nErrors with 403 if the current user has not set up TOTP or the code fails verification.",
        "operationId": "verifyTotpLegacy",
        "deprecated": true,
        "security": [
          {
            "SignerAuth": [
              "manage:mfa:verify:totp"
            ]
          }
        ]
      }
    },
    "/v0/user/orgs": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Retrieves all the orgs the user is a part of",
        "description": "Retrieves all the orgs the user is a part of",
        "operationId": "userOrgs",
        "security": [
          {
            "Oidc": []
          }
        ]
      }
    },
    "/v1/org/{org_id}/blob/sign/{key_id}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Raw Blob",
        "description": "Sign Raw Blob\n\nSigns an arbitrary blob with a given key.\n\n- ECDSA signatures are serialized as big-endian r and s plus recovery-id\nbyte v, which can in general take any of the values 0, 1, 2, or 3.\n\n- EdDSA signatures are serialized in the standard format.\n\n- BLS signatures are not supported on the blob-sign endpoint.",
        "operationId": "blobSign",
        "security": [
          {
            "SignerAuth": [
              "sign:blob"
            ]
          }
        ]
      }
    },
    "/v1/org/{org_id}/cube3signer/heartbeat": {
      "post": {
        "tags": [
          "Cube3Signer"
        ],
        "summary": "Record heartbeat",
        "description": "Record heartbeat\n\nThis endpoint is called by the cube3signer proxy to record various metrics to CloudWatch.",
        "operationId": "cube3signerHeartbeat",
        "security": [
          {
            "SignerAuth": []
          }
        ]
      }
    },
    "/v1/org/{org_id}/eth1/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign EVM Transaction",
        "description": "Sign EVM Transaction\n\nSigns an Ethereum (and other EVM) transaction with a given Secp256k1 key.\nReturns an RLP-encoded transaction with EIP-155 signature.\n\nThe key must be associated with the role and organization on whose behalf this action is called.",
        "operationId": "eth1Sign",
        "security": [
          {
            "SignerAuth": [
              "sign:evm:tx"
            ]
          }
        ]
      }
    },
    "/v1/org/{org_id}/eth2/sign/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Validator Request",
        "description": "Sign Validator Request\n\nSigns an eth2 validator request with a given BLS key.\n\nThe key must be associated with the role and organization on whose behalf this action is called.",
        "operationId": "eth2Sign",
        "security": [
          {
            "SignerAuth": [
              "sign:eth2:validate"
            ]
          }
        ]
      }
    },
    "/v1/org/{org_id}/eth2/stake": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Stake Deposit",
        "description": "Sign Stake Deposit\n\nSigns a deposit transaction with a `validator_key`. If `validator_key` is set to a pregenerated key, we use the\nprovided validator key. Otherwise, we generate a new BLS key.\n\nWhen using a pregenerated key, the key must be associated with the role and organization on whose\nbehalf this action is called.",
        "operationId": "stake",
        "security": [
          {
            "SignerAuth": [
              "sign:eth2:stake"
            ]
          }
        ]
      }
    },
    "/v1/org/{org_id}/eth2/unstake/{pubkey}": {
      "post": {
        "tags": [
          "Signing"
        ],
        "summary": "Sign Unstake Request",
        "description": "Sign Unstake Request\n\nHandle unstaking request, producing a signed voluntary exit message\nthat can be posted directly to the Beacon chain.\n\nThe key must be associated with the role and organization on whose behalf this action is called.",
        "operationId": "unstake",
        "security": [
          {
            "SignerAuth": [
              "sign:eth2:unstake"
            ]
          }
        ]
      }
    },
    "/v1/org/{org_id}/token/refresh": {
      "patch": {
        "tags": [
          "SignerSession"
        ],
        "summary": "Refresh Signer Session",
        "description": "Refresh Signer Session",
        "operationId": "signerSessionRefresh",
        "security": [
          {
            "SignerAuth": [
              ""
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oidc": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "description": "OIDC tokens allow users to authenticate using a third-party service. These are exchanged for signer session tokens."
      },
      "SignerAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "description": "Signing API end-points use session tokens for auth. Specifically, with each request you need to use the \\`token\\` from your signer session (which you create with `cs token create`)."
      }
    }
  },
  "security": [
    {
      "Cognito": []
    }
  ]
}
